version: '3.1'
services: 
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
        security_opt:
            - seccomp:unconfined
        #command: --init-file /data/application/dati.sql
        volumes: 
            - '../database/dati.sql:/data/application/dati.sql'
        network_mode: "host"
    server:
        build: .
        #network mode is incompatiple with port bndings
        #ports: 
        #    - "3000:3000"
        depends_on:
            - "db"
        volumes:
            - filesystem:/home/filesystem
        network_mode: "host"
volumes: 
    filesystem:
